from rest_framework.routers import DefaultRouter
from django.urls import path, include
from .views import (
    BusinessPerformanceMetricViewSet,
    EngagementMetricViewSet,
    ActiveSessionViewSet,
    LoginAttemptViewSet,
    SystemHealthIndicatorViewSet,
)
# Create a router and register ViewSets
router = DefaultRouter()
router.register(r'business-metrics', BusinessPerformanceMetricViewSet, basename='business-metrics')
router.register(r'engagement-metrics', EngagementMetricViewSet, basename='engagement-metrics')
router.register(r'active-sessions', ActiveSessionViewSet, basename='active-sessions')
router.register(r'login-attempts', LoginAttemptViewSet, basename='login-attempts')
router.register(r'system-health', SystemHealthIndicatorViewSet, basename='system-health')

# Define urlpatterns
urlpatterns = [
    path('', include(router.urls)),  # Include all routes generated by the router
]
