from rest_framework.routers import DefaultRouter
from django.urls import path, include
from rest_framework_simplejwt.views import TokenRefreshView, TokenObtainPairView
from .views import (
    BusinessPerformanceMetricViewSet,
    EngagementMetricViewSet,
    ActiveSessionViewSet,
    LoginAttemptViewSet,
    SystemHealthIndicatorViewSet,
    AnalyticsPageView,
)
# Create a router and register ViewSets
router = DefaultRouter()
router.register(r'business-metrics', BusinessPerformanceMetricViewSet, basename='business-metrics')
router.register(r'engagement-metrics', EngagementMetricViewSet, basename='engagement-metrics')
router.register(r'active-sessions', ActiveSessionViewSet, basename='active-sessions')
router.register(r'login-attempts', LoginAttemptViewSet, basename='login-attempts')
router.register(r'system-health', SystemHealthIndicatorViewSet, basename='system-health')

app_name= "analytics"
# Define urlpatterns
urlpatterns = [
    path('api/', include(router.urls)),  # Include all routes generated by the router
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path("", AnalyticsPageView.as_view(), name="analytics_page"),# Page route for analytics
]
