# Generated by Django 5.1.2 on 2024-11-11 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the folder, e.g., 'Documentation'.", max_length=100)),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the project.', max_length=100)),
                ('description', models.TextField(help_text='Detailed description of the project.')),
                ('date', models.DateField(help_text='Date of project completion or start date.')),
                ('technologies', models.CharField(help_text='Comma-separated list of technologies used.', max_length=200)),
                ('public_url', models.URLField(blank=True, help_text='Public link, e.g., GitHub or live demo.', null=True)),
                ('private_url', models.URLField(blank=True, help_text='Private link, e.g., Google Drive or restricted resource.', null=True)),
                ('is_public', models.BooleanField(default=True, help_text='Flag to indicate if project is publicly visible.')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the file, e.g., 'Project_Plan.pdf'.", max_length=100)),
                ('file', models.FileField(help_text='File to be uploaded for the project.', upload_to='project_files/')),
                ('is_private', models.BooleanField(default=False, help_text='Flag to indicate if the file is private.')),
                ('folder', models.ForeignKey(help_text='The folder to which this file belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='portfolio.folder')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.AddField(
            model_name='folder',
            name='project',
            field=models.ForeignKey(help_text='The project to which this folder belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='portfolio.project'),
        ),
    ]
