# Generated by Django 5.1.1 on 2024-11-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address for contacting the site owner.', max_length=254)),
                ('linkedin_url', models.URLField(help_text='URL of the LinkedIn profile.')),
                ('github_url', models.URLField(help_text='URL of the GitHub profile.')),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
            },
        ),
    ]
