# Generated by Django 5.1.1 on 2024-11-15 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_jobexperience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='linkedin_url',
        ),
    ]
