# Generated by Django 5.1.1 on 2024-11-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the certificate.', max_length=255)),
                ('description', models.TextField(help_text='Description of the course.')),
                ('link', models.URLField(help_text='URL to the certificate or course information.')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(help_text='Name of the educational institution.', max_length=255)),
                ('degree', models.CharField(choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('PhD', 'PhD'), ('Other', 'Other')], help_text="Degree type (e.g., Bachelor's, Master's).", max_length=50)),
                ('field_of_study', models.CharField(help_text='Field of study (e.g., Computer Science).', max_length=255)),
                ('start_date', models.DateField(help_text='Start date of the program.')),
                ('end_date', models.DateField(help_text='End date of the program, or expected end date.')),
                ('description', models.TextField(blank=True, help_text='Optional description of the program or notable achievements.')),
            ],
        ),
    ]
