# Generated by Django 5.1.1 on 2024-11-13 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_certificate_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(help_text='Name of the reviewer submitting the review.', max_length=100)),
                ('content', models.TextField(help_text='Content of the review.')),
                ('recommendation', models.BooleanField(default=False, help_text='Does the reviewer recommend this project?')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval status of the review.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for when the review was created.')),
                ('project', models.ForeignKey(help_text='The project this review is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='portfolio.project')),
            ],
        ),
    ]
