# Generated by Django 5.1.1 on 2024-11-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the category.', max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier for the category (auto-generated).', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the blog post.', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier for the post (auto-generated).', max_length=200, unique=True)),
                ('content', models.TextField(help_text='Main content of the blog post.')),
                ('excerpt', models.TextField(blank=True, help_text='Short summary or excerpt of the blog post.')),
                ('featured_image', models.ImageField(blank=True, help_text='Optional featured image for the blog post.', null=True, upload_to='blog_images/')),
                ('publication_date', models.DateField(auto_now_add=True, help_text='Date the blog post was published.')),
                ('author', models.CharField(help_text='Author of the blog post.', max_length=100)),
                ('categories', models.ManyToManyField(help_text='Categories associated with the blog post.', related_name='blog_posts', to='portfolio.category')),
            ],
        ),
    ]
