# Generated by Django 5.1.2 on 2024-11-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_certificate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='field',
            field=models.CharField(blank=True, help_text='Optional field to specify the category or context of the certificate.', max_length=255, null=True),
        ),
    ]
