# Generated by Django 5.1.2 on 2024-11-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_certificate_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='google_file_id',
            field=models.CharField(blank=True, help_text='Google File ID for embedding a presentation.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(help_text='Description content for the section', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(help_text='Title of the section', max_length=200, verbose_name='Title'),
        ),
    ]
