# Generated by Django 5.1.2 on 2024-11-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_contactinfo_github_url_contactinfo_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for the certificate.', null=True, upload_to='certificate_images/'),
        ),
    ]
