# Generated by Django 5.1.2 on 2024-12-11 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_project_google_file_id_alter_section_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Certificate', 'verbose_name_plural': 'Certificates'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Education', 'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='jobexperience',
            options={'verbose_name': 'Job Experience', 'verbose_name_plural': 'Job Experiences'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(help_text='Author of the blog post.', max_length=100, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='categories',
            field=models.ManyToManyField(help_text='Categories associated with the blog post.', related_name='blog_posts', to='portfolio.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text='Main content of the blog post.', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short summary or excerpt of the blog post.', verbose_name='Excerpt'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Optional featured image for the blog post.', null=True, upload_to='blog_images/', verbose_name='Featured Image'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='publication_date',
            field=models.DateField(auto_now_add=True, help_text='Date the blog post was published.', verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier for the post (auto-generated).', max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(help_text='Title of the blog post.', max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Name of the category.', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly identifier for the category (auto-generated).', max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=models.TextField(help_text='Description of the course.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='field',
            field=models.CharField(blank=True, help_text='Optional field to specify the category or context of the certificate.', max_length=255, null=True, verbose_name='Field'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for the certificate.', null=True, upload_to='certificate_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='link',
            field=models.URLField(help_text='URL to the certificate or course information.', verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Skills related to this certificate.', related_name='certificates', to='portfolio.skill', verbose_name='Skills'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(help_text='The title of the certificate.', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(help_text='Email address for contacting the site owner.', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub profile URL of the site owner.', null=True, verbose_name='GitHub URL'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL of the site owner.', null=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('PhD', 'PhD'), ('Other', 'Other')], help_text="Degree type (e.g., Bachelor's, Master's).", max_length=50, verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the program or notable achievements.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_date',
            field=models.DateField(help_text='End date of the program, or expected end date.', verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(help_text='Field of study (e.g., Computer Science).', max_length=255, verbose_name='Field of Study'),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(help_text='Name of the educational institution.', max_length=255, verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='education',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Skills related to this educational entry.', related_name='educations', to='portfolio.skill', verbose_name='Skills'),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(help_text='Start date of the program.', verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(help_text='File to be uploaded for the project.', upload_to='project_files/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(help_text='The folder to which this file belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='portfolio.folder', verbose_name='Folder'),
        ),
        migrations.AlterField(
            model_name='file',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Flag to indicate if the file is private.', verbose_name='Is Private'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(help_text="Name of the file, e.g., 'Project_Plan.pdf'.", max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(help_text="Name of the folder, e.g., 'Documentation'.", max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='project',
            field=models.ForeignKey(help_text='The project to which this folder belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='portfolio.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='jobexperience',
            name='company',
            field=models.CharField(help_text='Company name', max_length=255, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='jobexperience',
            name='description',
            field=models.TextField(blank=True, help_text='Description of responsibilities or achievements', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='jobexperience',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date of the job (if applicable)', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='jobexperience',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Skills related to this job experience', related_name='job_experiences', to='portfolio.skill', verbose_name='Skills'),
        ),
        migrations.AlterField(
            model_name='jobexperience',
            name='start_date',
            field=models.DateField(help_text='Start date of the job', verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='jobexperience',
            name='title',
            field=models.CharField(help_text='Job title (e.g., Software Developer)', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(help_text='Date of project completion or start date.', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Detailed description of the project.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='google_file_id',
            field=models.CharField(blank=True, help_text='Google File ID for embedding a presentation.', max_length=100, null=True, verbose_name='Google File ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Flag to indicate if project is publicly visible.', verbose_name='Is Public'),
        ),
        migrations.AlterField(
            model_name='project',
            name='private_url',
            field=models.URLField(blank=True, help_text='Private link, e.g., Google Drive or restricted resource.', null=True, verbose_name='Private URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='public_url',
            field=models.URLField(blank=True, help_text='Public link, e.g., GitHub or live demo.', null=True, verbose_name='Public URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(help_text='Comma-separated list of technologies used.', max_length=200, verbose_name='Technologies'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Title of the project.', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(help_text='Content of the review.', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp for when the review was created.', verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='review',
            name='project',
            field=models.ForeignKey(help_text='The project this review is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='portfolio.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='review',
            name='recommendation',
            field=models.BooleanField(default=False, help_text='Does the reviewer recommend this project?', verbose_name='Recommendation'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(help_text='Name of the reviewer submitting the review.', max_length=100, verbose_name='Reviewer Name'),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval status of the review.', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(help_text='The name of the skill (e.g., Python, Data Analysis).', max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
