# Generated by Django 5.1.2 on 2024-12-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_remove_skill_name_en_remove_skill_name_it_skill_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='name',
        ),
        migrations.AddField(
            model_name='skill',
            name='name_en',
            field=models.CharField(default=1, help_text='The name of the skill in English (e.g., Python, Data Analysis).', max_length=100, verbose_name='Name (EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='name_it',
            field=models.CharField(default='python', help_text='The name of the skill in Italian (e.g., Python, Analisi dei dati).', max_length=100, verbose_name='Name (IT)'),
            preserve_default=False,
        ),
    ]
