# Generated by Django 5.1.2 on 2024-12-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_remove_skill_name_skill_name_en_skill_name_it'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='field_en',
            field=models.CharField(blank=True, help_text='Field of the certificate in English.', max_length=255, null=True, verbose_name='Field (EN)'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='field_it',
            field=models.CharField(blank=True, help_text='Field of the certificate in Italian.', max_length=255, null=True, verbose_name='Field (IT)'),
        ),
    ]
