# Generated by Django 5.1.2 on 2024-12-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_certificate_field_en_certificate_field_it'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='description_en',
            field=models.TextField(blank=True, help_text='Detailed description of the folder in English.', null=True, verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='folder',
            name='description_it',
            field=models.TextField(blank=True, help_text='Detailed description of the folder in Italian.', null=True, verbose_name='Description (IT)'),
        ),
    ]
