# Generated by Django 5.1.2 on 2024-12-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_folder_description_en_folder_description_it'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='onedrive_file_id',
            field=models.CharField(blank=True, help_text='OneDrive File ID for embedding a presentation', max_length=255, null=True, verbose_name='OneDrive_ID'),
        ),
    ]
