# Generated by Django 5.1.2 on 2024-12-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_project_onedrive_file_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='onedrive_file_id',
        ),
        migrations.AddField(
            model_name='project',
            name='onedrive_share_link',
            field=models.URLField(blank=True, help_text='OneDrive share link for embedding a presentation', max_length=2000, null=True, verbose_name='OneDrive_Link'),
        ),
    ]
