# Generated by Django 5.1.2 on 2024-12-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_remove_file_file_file_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='image',
        ),
        migrations.AddField(
            model_name='certificate',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of the certificate image.', null=True, verbose_name='Image URL'),
        ),
    ]
